"""Initial migration - create all tables

Revision ID: b764e0df6a95
Revises: 
Create Date: 2025-12-27 12:08:06.980526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b764e0df6a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create schemas first
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    op.execute('CREATE SCHEMA IF NOT EXISTS activities')
    op.execute('CREATE SCHEMA IF NOT EXISTS calendar')
    op.execute('CREATE SCHEMA IF NOT EXISTS documents')
    op.execute('CREATE SCHEMA IF NOT EXISTS emails')
    op.execute('CREATE SCHEMA IF NOT EXISTS tasks')
    op.execute('CREATE SCHEMA IF NOT EXISTS integrations')
    op.execute('CREATE SCHEMA IF NOT EXISTS notifications')
    op.execute('CREATE SCHEMA IF NOT EXISTS relationships')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('imap_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('smtp_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caldav_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='users'
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False, schema='users')
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='activities'
    )
    op.create_index('idx_activities_entity', 'activities', ['entity_type', 'entity_id'], unique=False, schema='activities')
    op.create_index('idx_activities_type', 'activities', ['action_type'], unique=False, schema='activities')
    op.create_index('idx_activities_user', 'activities', ['user_id', 'created_at'], unique=False, schema='activities')
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('calendar_color', sa.String(length=7), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='calendar'
    )
    op.create_index('idx_events_range', 'calendar_events', ['user_id', 'start_time', 'end_time'], unique=False, schema='calendar')
    op.create_index('idx_events_start', 'calendar_events', ['start_time'], unique=False, schema='calendar')
    op.create_index('idx_events_user', 'calendar_events', ['user_id'], unique=False, schema='calendar')
    op.create_table('document_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='documents'
    )
    op.create_index('idx_doc_tags_user', 'document_tags', ['user_id'], unique=False, schema='documents')
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_medium', sa.Text(), nullable=True),
    sa.Column('summary_long', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("processing_status IN ('queued', 'processing', 'complete', 'failed')", name='check_processing_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='documents'
    )
    op.create_index('idx_documents_status', 'documents', ['processing_status'], unique=False, schema='documents')
    op.create_index('idx_documents_type', 'documents', ['file_type'], unique=False, schema='documents')
    op.create_index('idx_documents_user', 'documents', ['user_id'], unique=False, schema='documents')
    op.create_table('emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('to_emails', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cc_emails', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('bcc_emails', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id'),
    schema='emails'
    )
    op.create_index('idx_emails_date', 'emails', ['date'], unique=False, schema='emails')
    op.create_index('idx_emails_folder', 'emails', ['folder'], unique=False, schema='emails')
    op.create_index('idx_emails_thread', 'emails', ['thread_id'], unique=False, schema='emails')
    op.create_index('idx_emails_user', 'emails', ['user_id'], unique=False, schema='emails')
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_logs_status', 'integration_logs', ['status'], unique=False)
    op.create_index('idx_integration_logs_user', 'integration_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_integration_logs_workflow', 'integration_logs', ['workflow_name'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='notifications'
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False, schema='notifications')
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False, schema='notifications')
    op.create_index('idx_notifications_type', 'notifications', ['type'], unique=False, schema='notifications')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False, schema='notifications')
    op.create_table('entity_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('email', 'task', 'calendar', 'document')", name='check_entity_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationships'
    )
    op.create_index('idx_entity_embeddings_type', 'entity_embeddings', ['entity_type', 'entity_id'], unique=False, schema='relationships')
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.String(length=20), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_type', sa.String(length=20), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_by IN ('user', 'agent')", name='check_relationship_created_by'),
    sa.CheckConstraint("from_type IN ('email', 'task', 'calendar', 'document')", name='check_from_type'),
    sa.CheckConstraint("to_type IN ('email', 'task', 'calendar', 'document')", name='check_to_type'),
    sa.CheckConstraint('strength >= 0 AND strength <= 1', name='check_strength_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='relationships'
    )
    op.create_index('idx_relationships_from', 'relationships', ['from_type', 'from_id'], unique=False, schema='relationships')
    op.create_index('idx_relationships_strength', 'relationships', ['strength'], unique=False, schema='relationships')
    op.create_index('idx_relationships_to', 'relationships', ['to_type', 'to_id'], unique=False, schema='relationships')
    op.create_index('idx_relationships_user', 'relationships', ['user_id'], unique=False, schema='relationships')
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('context_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sessions'
    )
    op.create_index('idx_sessions_last_activity', 'sessions', ['last_activity'], unique=False, schema='sessions')
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False, schema='sessions')
    op.create_table('task_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_table('task_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index('idx_lists_user', 'task_lists', ['user_id', 'position'], unique=False, schema='tasks')
    op.create_table('calendar_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('invitee_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'declined', 'tentative')", name='check_invitation_status'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar.calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='calendar'
    )
    op.create_index('idx_invitations_event', 'calendar_invitations', ['event_id'], unique=False, schema='calendar')
    op.create_table('document_tag_assignments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['documents.document_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id'),
    schema='documents'
    )
    op.create_index('idx_doc_tags_doc', 'document_tag_assignments', ['document_id'], unique=False, schema='documents')
    op.create_index('idx_doc_tags_tag', 'document_tag_assignments', ['tag_id'], unique=False, schema='documents')
    op.create_table('email_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='emails'
    )
    op.create_index('idx_attachments_email', 'email_attachments', ['email_id'], unique=False, schema='emails')
    op.create_table('email_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reply_to_email_id', sa.UUID(), nullable=True),
    sa.Column('to_emails', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cc_emails', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('bcc_emails', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_by IN ('user', 'agent')", name='check_draft_created_by'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'discarded')", name='check_draft_status'),
    sa.ForeignKeyConstraint(['reply_to_email_id'], ['emails.emails.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='emails'
    )
    op.create_index('idx_drafts_status', 'email_drafts', ['status'], unique=False, schema='emails')
    op.create_index('idx_drafts_user', 'email_drafts', ['user_id'], unique=False, schema='emails')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("message_type IN ('text', 'audio')", name='check_message_type'),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='check_message_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='messages'
    )
    op.create_index('idx_messages_created', 'messages', ['created_at'], unique=False, schema='messages')
    op.create_index('idx_messages_session', 'messages', ['session_id'], unique=False, schema='messages')
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vertical_position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=10), nullable=False),
    sa.Column('extracted_from', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("created_by IN ('user', 'agent')", name='check_created_by'),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high')", name='check_task_priority'),
    sa.CheckConstraint("status IN ('backlog', 'open', 'in_progress', 'waiting', 'done', 'pending', 'dismissed')", name='check_task_status'),
    sa.ForeignKeyConstraint(['list_id'], ['tasks.task_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index('idx_tasks_due', 'tasks', ['due_date'], unique=False, schema='tasks')
    op.create_index('idx_tasks_list', 'tasks', ['list_id', 'vertical_position'], unique=False, schema='tasks')
    op.create_index('idx_tasks_parent', 'tasks', ['parent_id'], unique=False, schema='tasks')
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False, schema='tasks')
    op.create_index('idx_tasks_user', 'tasks', ['user_id'], unique=False, schema='tasks')
    op.create_table('llm_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='messages'
    )
    op.create_index('idx_llm_requests_created', 'llm_requests', ['created_at'], unique=False, schema='messages')
    op.create_index('idx_llm_requests_user', 'llm_requests', ['user_id', 'created_at'], unique=False, schema='messages')
    op.create_table('task_tags',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['tasks.task_labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'label_id'),
    schema='tasks'
    )
    op.create_index('idx_task_tags_label', 'task_tags', ['label_id'], unique=False, schema='tasks')
    op.create_index('idx_task_tags_task', 'task_tags', ['task_id'], unique=False, schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_tags_task', table_name='task_tags', schema='tasks')
    op.drop_index('idx_task_tags_label', table_name='task_tags', schema='tasks')
    op.drop_table('task_tags', schema='tasks')
    op.drop_index('idx_llm_requests_user', table_name='llm_requests', schema='messages')
    op.drop_index('idx_llm_requests_created', table_name='llm_requests', schema='messages')
    op.drop_table('llm_requests', schema='messages')
    op.drop_index('idx_tasks_user', table_name='tasks', schema='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks', schema='tasks')
    op.drop_index('idx_tasks_parent', table_name='tasks', schema='tasks')
    op.drop_index('idx_tasks_list', table_name='tasks', schema='tasks')
    op.drop_index('idx_tasks_due', table_name='tasks', schema='tasks')
    op.drop_table('tasks', schema='tasks')
    op.drop_index('idx_messages_session', table_name='messages', schema='messages')
    op.drop_index('idx_messages_created', table_name='messages', schema='messages')
    op.drop_table('messages', schema='messages')
    op.drop_index('idx_drafts_user', table_name='email_drafts', schema='emails')
    op.drop_index('idx_drafts_status', table_name='email_drafts', schema='emails')
    op.drop_table('email_drafts', schema='emails')
    op.drop_index('idx_attachments_email', table_name='email_attachments', schema='emails')
    op.drop_table('email_attachments', schema='emails')
    op.drop_index('idx_doc_tags_tag', table_name='document_tag_assignments', schema='documents')
    op.drop_index('idx_doc_tags_doc', table_name='document_tag_assignments', schema='documents')
    op.drop_table('document_tag_assignments', schema='documents')
    op.drop_index('idx_invitations_event', table_name='calendar_invitations', schema='calendar')
    op.drop_table('calendar_invitations', schema='calendar')
    op.drop_index('idx_lists_user', table_name='task_lists', schema='tasks')
    op.drop_table('task_lists', schema='tasks')
    op.drop_table('task_labels', schema='tasks')
    op.drop_index('idx_sessions_user', table_name='sessions', schema='sessions')
    op.drop_index('idx_sessions_last_activity', table_name='sessions', schema='sessions')
    op.drop_table('sessions', schema='sessions')
    op.drop_index('idx_relationships_user', table_name='relationships', schema='relationships')
    op.drop_index('idx_relationships_to', table_name='relationships', schema='relationships')
    op.drop_index('idx_relationships_strength', table_name='relationships', schema='relationships')
    op.drop_index('idx_relationships_from', table_name='relationships', schema='relationships')
    op.drop_table('relationships', schema='relationships')
    op.drop_index('idx_entity_embeddings_type', table_name='entity_embeddings', schema='relationships')
    op.drop_table('entity_embeddings', schema='relationships')
    op.drop_index('idx_notifications_user_id', table_name='notifications', schema='notifications')
    op.drop_index('idx_notifications_type', table_name='notifications', schema='notifications')
    op.drop_index('idx_notifications_is_read', table_name='notifications', schema='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications', schema='notifications')
    op.drop_table('notifications', schema='notifications')
    op.drop_index('idx_integration_logs_workflow', table_name='integration_logs')
    op.drop_index('idx_integration_logs_user', table_name='integration_logs')
    op.drop_index('idx_integration_logs_status', table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index('idx_emails_user', table_name='emails', schema='emails')
    op.drop_index('idx_emails_thread', table_name='emails', schema='emails')
    op.drop_index('idx_emails_folder', table_name='emails', schema='emails')
    op.drop_index('idx_emails_date', table_name='emails', schema='emails')
    op.drop_table('emails', schema='emails')
    op.drop_index('idx_documents_user', table_name='documents', schema='documents')
    op.drop_index('idx_documents_type', table_name='documents', schema='documents')
    op.drop_index('idx_documents_status', table_name='documents', schema='documents')
    op.drop_table('documents', schema='documents')
    op.drop_index('idx_doc_tags_user', table_name='document_tags', schema='documents')
    op.drop_table('document_tags', schema='documents')
    op.drop_index('idx_events_user', table_name='calendar_events', schema='calendar')
    op.drop_index('idx_events_start', table_name='calendar_events', schema='calendar')
    op.drop_index('idx_events_range', table_name='calendar_events', schema='calendar')
    op.drop_table('calendar_events', schema='calendar')
    op.drop_index('idx_activities_user', table_name='activities', schema='activities')
    op.drop_index('idx_activities_type', table_name='activities', schema='activities')
    op.drop_index('idx_activities_entity', table_name='activities', schema='activities')
    op.drop_table('activities', schema='activities')
    op.drop_index('idx_users_email', table_name='users', schema='users')
    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
